### ISSUE TITLE
Cannot serialize null string when serializing with length prefix

### ISSUE THREAD

**Issue by aienabled** [AqlaSolutions/AqlaSerializer#10]
Hello!
When I'm using `public void SerializeWithLengthPrefix(Stream dest, object value, Type type, PrefixStyle style, int fieldNumber, SerializationContext context)`.
for serializing null string with `PrefixStyle.Base128` I've got this exception:
`System.NullReferenceException: Object reference not set to an instance of an object.
    at AqlaSerializer.ProtoWriter.WriteObject(Object value, Int32 key, ProtoWriter writer, PrefixStyle style, Int32 fieldNumber, Boolean isRoot) in C:\Projects\Games\LibsSources\Aqla\Serializer\AqlaSerializer\protobuf-net\ProtoWriter.cs:line 160`

Is that by-design or a bug?

Regards!

**Comment by aienabled** [comment]
It seems the question could be extending to serializing any nullable root objects.

**Comment by AqlaSolutions** [comment]
@aienabled serializing nullable root is not supported by design. You can wrap your nullable objects into a generic container.

**Comment by aienabled** [comment]
@AqlaSolutions, ok, so I will need to wrap these objects into some generic container. No problem, thanks!
