### ISSUE TITLE
Cannot compile latest source from Master

### ISSUE THREAD

**Issue by aienabled** [AqlaSolutions/AqlaSerializer#12]
Hello!

I just pulled Master HEAD and cannot build it:

https://raw.githubusercontent.com/AqlaSolutions/AqlaSerializer/master/protobuf-net/Serializers/WillSetFieldWireType/Collections/MultiDimensionalArrayDecorator.cs
Error on line 309

``` C#
    g.If(valueArr.AsOperand != null && optionalOutOldFirstDimLength > 0);
```

Error message:

>  In order to be applicable as a short circuit operator a user-defined logical operator ('ContextualOperand.operator &(ContextualOperand, Operand)') must have the same return type and parameter type.

(FEAT_COMPILER conditional compilation symbol is used)

Regards!

**Comment by AqlaSolutions** [comment]
@aienabled you need to use the latest RunSharp version which should be downloaded separately

**Comment by aienabled** [comment]
Indeed!
Thanks, sorry for false issue :-).
