### ISSUE TITLE
MetaType.ArrayLengthReadLimit

### ISSUE THREAD

**Issue by Gl237man** [AqlaSolutions/AqlaSerializer#19]
how set MetaType.ArrayLengthReadLimit?

**Comment by AqlaSolutions** [comment]
`RuntimeTypeModel.Default.Add(type, true).ArrayLengthReadLimit = x`

**Comment by AqlaSolutions** [comment]
As alternative you can use `List<T>` without modifying settings.

**Comment by Gl237man** [comment]
Thank you, it helped me a lot.
