### ISSUE TITLE
Support More Useful .NET Types for Serialization

### ISSUE THREAD

**Issue by ab-tools** [AqlaSolutions/AqlaSerializer#2]
One point which I always found very bothersome with protobuf-net was their limited support for serialization of several very useful and often used .NET types in data structures.

For me especially the types from the "System.Drawing" namespace would be very interesting, in particular:
- Color
- Point
- Rectangle
- RectangleF
- if possible also: Image (which should also be easy to implement by using "Image.FromStream()" and "Image.Save()" methods)

I know I can work around that with e. g. 

```
public Color Color { get; set; }

    [SerializableMember(1)]
    private int ColorProto {
        get { return Color.ToArgb(); }
        set { Color = Color.FromArgb(value); }
    }
```

for Color and e. g.

```
    public Point MainWindowLocation { get; set; }

    [SerializableMember(101)]
    private ProtoPoint MainWindowLocationProto
    {
        get
        {
            return new ProtoPoint(MainWindowLocation.X, MainWindowLocation.Y);
        }
        set
        {
            MainWindowLocation = new Point(value.X, value.Y);
        }
    }

[SerializableType(ImplicitFields = ImplicitFieldsMode.None, NotAsReferenceDefault = true)]
internal class ProtoPoint
{
    [SerializableMember(1)]
    public int X { get; set; }

    [SerializableMember(2)]
    public int Y { get; set; }

    public ProtoPoint(int x, int y)
    {
        this.X = x;
        this.Y = y;
    }

    private ProtoPoint()
    {
    }
}
```

for Point, but as you can easily see that gets longish very quickly and is really bothersome to use such work-arounds here as it even make serialization/deserialization slower when such "useless" extra objects need to be created all the time.

Would you mind supporting these types directly with AqlaSerializer?

Thanks a lot in advance again for your great support
Andreas

**Comment by AqlaSolutions** [comment]
@ab-tools 
You can use surrogates. This is a feature of the original protobuf-net. See http://stackoverflow.com/questions/7046506/can-i-serialize-arbitrary-types-with-protobuf-net

**Comment by ab-tools** [comment]
Again thank you for this very quick reply! :-)

True, this Surrogate approach at least cleans up the code a bit (will change my current work-around in this way). But technically it makes no difference (correct me if I should be wrong):
for each instance (and there are 100,000s of them) of Point, Rectangle, ... used in the data structure an additional (useless) object needs to be created on serialization and deserialization.

But with a direct support of these types this would not be needed.

**Comment by AqlaSolutions** [comment]
@ab-tools 
I'm not 100% sure but you can use structs (not classes) as surrogates to not clutter up heap. If it's possible then performance hit should be negligibly small.

**Comment by ab-tools** [comment]
Good idea, works good - also with struct!

Then I will leave it like this and use your solution starting from now (I already removed all the legacy "protobuf" attributes ;-) ). It's definitely a progress compared to protobuf-net!

Thanks again for the great support
Andreas
