### ISSUE TITLE
Does class fields get serialized by default?

### ISSUE THREAD

**Issue by inethui** [AqlaSolutions/AqlaSerializer#23]
According to the wiki, public class properties are serialized by default. How about class fields? Do we need to mark them with protobuf attribute?

**Comment by AqlaSolutions** [comment]
You need to either specify `ImplicitFields = ImplicitFieldsMode.PublicFieldsAndProperties ` in the class attribute or use `[SerializableMember]` attribute on a field.

**Comment by AqlaSolutions** [comment]
Oops, `ImplicitFieldsMode.PublicFieldsAndProperties `

**Comment by inethui** [comment]
Thanks for the quick reply. If I understand correctly, we can make public fields and properties serialized by default. How about private fields? Can we make them automatically serialized?

**Comment by AqlaSolutions** [comment]
`ImplicitFieldsMode.AllFieldsAndProperties`
