### ISSUE TITLE
Type System.Double can't be handled as reference

### ISSUE THREAD

**Issue by inethui** [AqlaSolutions/AqlaSerializer#24]
The following code generates error message "Type System.Double can't be handled as reference", which I don't understand. I think the code should work, instead of failing with some weird messages. Can you take a look please?

        [Test]
        public void RegisterCollectionClassWithMemberFields()
        {
            var model = RuntimeTypeModel.Default;

            var metaType = model.Add(typeof(WithCollectionClassWithMemberFields), true);
            metaType.AsReferenceDefault = true;
            metaType.UseConstructor = false;

            var metaType2 = model.Add(typeof(CollectionClassWithArrayField), true);
            metaType2.AsReferenceDefault = true;
            metaType2.UseConstructor = false;

            var metaField = metaType.AddField(1, "_collectionClassWithMemberFields");
            metaField.AsReference = true;

            var metaField2 = metaType2.AddField(1, "_params");
            metaField2.AsReference = true;

            model.CompileInPlace();
        }
            
        [Serializable]
        private class WithCollectionClassWithMemberFields
        {
            private readonly CollectionClassWithArrayField _collectionClassWithArrayFields;

            public WithCollectionClassWithMemberFields(CollectionClassWithArrayField collectionClassWithMemberFields)
            {
                _collectionClassWithArrayFields = collectionClassWithMemberFields;
            }
        }

        [Serializable]
        private class CollectionClassWithArrayField : IList<double>
        {
            private double[] _params;

            public CollectionClassWithArrayField(int size)
            {
                _params = new double[size];
            }

            public double this[int index]
            {
                get
                {
                    throw new NotImplementedException();
                }

                set
                {
                    throw new NotImplementedException();
                }
            }

            public int Count
            {
                get
                {
                    throw new NotImplementedException();
                }
            }

            public bool IsReadOnly
            {
                get
                {
                    throw new NotImplementedException();
                }
            }

            public void Add(double item)
            {
                throw new NotImplementedException();
            }

            public void Clear()
            {
                throw new NotImplementedException();
            }

            public bool Contains(double item)
            {
                throw new NotImplementedException();
            }

            public void CopyTo(double[] array, int arrayIndex)
            {
                throw new NotImplementedException();
            }

            public IEnumerator<double> GetEnumerator()
            {
                throw new NotImplementedException();
            }

            public int IndexOf(double item)
            {
                throw new NotImplementedException();
            }

            public void Insert(int index, double item)
            {
                throw new NotImplementedException();
            }

            public bool Remove(double item)
            {
                throw new NotImplementedException();
            }

            public void RemoveAt(int index)
            {
                throw new NotImplementedException();
            }

            IEnumerator IEnumerable.GetEnumerator()
            {
                throw new NotImplementedException();
            }
        }

**Comment by AqlaSolutions** [comment]
using AqlaSerializer.Meta;
    
    namespace ConsoleApp5
    {
        public class Test
        {
            public void RegisterCollectionClassWithMemberFields()
            {
                var model = RuntimeTypeModel.Default;
    
                var metaType = model.Add(typeof(WithCollectionClassWithMemberFields), true);
                metaType.AsReferenceDefault = true;
                metaType.UseConstructor = false;
    
                var metaType2 = model.Add(typeof(CollectionClassWithArrayField), true);
                metaType2.AsReferenceDefault = true;
                metaType2.UseConstructor = false;
                metaType2.IgnoreListHandling = true;
    
                var metaField = metaType.AddField(1, "_collectionClassWithArrayFields");
                metaField.SetSettings(x => x.V.Format = AqlaSerializer.ValueFormat.Reference, 0);
    
                var metaField2 = metaType2.AddField(1, "_params");
                metaField2.SetSettings(x => x.V.Format = AqlaSerializer.ValueFormat.Reference, 0);
    
                model.CompileInPlace();
            }
    
            [Serializable]
            private class WithCollectionClassWithMemberFields
            {
                private readonly CollectionClassWithArrayField _collectionClassWithArrayFields;
    
                public WithCollectionClassWithMemberFields(CollectionClassWithArrayField collectionClassWithMemberFields)
                {
                    _collectionClassWithArrayFields = collectionClassWithMemberFields;
                }
            }
    
            [Serializable]
            private class CollectionClassWithArrayField : IList<double>
            {
                private readonly double[] _params;
    
                public CollectionClassWithArrayField(int size)
                {
                    _params = new double[size];
                }
    
                public double this[int index]
                {
                    get
                    {
                        throw new NotImplementedException();
                    }
    
                    set
                    {
                        throw new NotImplementedException();
                    }
                }
    
                public int Count
                {
                    get
                    {
                        throw new NotImplementedException();
                    }
                }
    
                public bool IsReadOnly
                {
                    get
                    {
                        throw new NotImplementedException();
                    }
                }
    
                public void Add(double item)
                {
                    throw new NotImplementedException();
                }
    
                public void Clear()
                {
                    throw new NotImplementedException();
                }
    
                public bool Contains(double item)
                {
                    throw new NotImplementedException();
                }
    
                public void CopyTo(double[] array, int arrayIndex)
                {
                    throw new NotImplementedException();
                }
    
                public IEnumerator<double> GetEnumerator()
                {
                    throw new NotImplementedException();
                }
    
                public int IndexOf(double item)
                {
                    throw new NotImplementedException();
                }
    
                public void Insert(int index, double item)
                {
                    throw new NotImplementedException();
                }
    
                public bool Remove(double item)
                {
                    throw new NotImplementedException();
                }
    
                public void RemoveAt(int index)
                {
                    throw new NotImplementedException();
                }
    
                System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
                {
                    throw new NotImplementedException();
                }
            }
        }
    }

**Comment by AqlaSolutions** [comment]
`AsReference` changes settings for all levels where `double[]` is level 0 and `double` is level 1. You need to change settings only for level 0. This is why it's marked obsolete.

**Comment by inethui** [comment]
Thanks for the solution. I'm using reflections to setup the default model. We have more than 10k classes.  Is it possible to make the Aqla APIs more easily to use? For example, AsReference only change level 0 by default. Also, can Aqla be enhanced to automatically detect the double array and setup the levels accordingly. I'm not sure how to determine the levels in our reflection-based code.

**Comment by AqlaSolutions** [comment]
AsReference is an obsolete member inherited from protobuf-net and must retain its semantics. I have no plans to change behavior of obsolete members.

**Comment by inethui** [comment]
Can Aqla be enhanced to automatically detect the double array and setup the levels accordingly?

**Comment by AqlaSolutions** [comment]
Please see https://github.com/AqlaSolutions/AqlaSerializer/wiki/Member-Formats#defaults

You don't need to manually set members `AsReference`, it works automatically.
