### ISSUE TITLE
How to defined sub-type of open generic type?

### ISSUE THREAD

**Issue by inethui** [AqlaSolutions/AqlaSerializer#25]
I have two generic classes (A and B) defined as below. B is a subtype of A. However, my setup doesn't work. I got an error like "Unexpected sub-type B". Any suggestion on how to make it work?
    
    public static class Test
    {
        public static void Main(string[] args)
        {
            var b = new B<int>(1, 2);
            var clone = Serializer.DeepClone(b);
    
            if (clone.Member2 != b.Member2 || clone.Member != b.Member)
                throw new Exception("clone failed");
    
            Console.WriteLine("clone success");
            Console.WriteLine("Press any key to continue ...");
            Console.ReadKey();
        }
    }
    
    [SerializableType(ImplicitFields = ImplicitFieldsMode.AllFields, SkipConstructor = true)]
    public class A<T>
    {
        private T _member;
    
        public A(T member)
        {
            _member = member;
        }
    
        public T Member => _member;
    }
    
    [SerializableType(ImplicitFields = ImplicitFieldsMode.AllFields, SkipConstructor = true)]
    [SerializeDerivedType(1, typeof(A<>))]
    public class B<T> : A<T>
    {
        private T member2;
    
        public B(T member, T member2)
            : A(member)
        {
            member2 = member2;
        }
    
        public T Member2 => member2;
    }

**Comment by AqlaSolutions** [comment]
It's not possible to define a subtype of an open generic. You should specify exact subtypes. Also you should use attribute on a base type, not subtype. Please read wiki: https://github.com/AqlaSolutions/AqlaSerializer/wiki/Versioning-and-field-numbers#hierarchy

    [SerializeDerivedType(1, typeof(B<int>))]
    [SerializeDerivedType(2, typeof(B<string>))]
    [SerializeDerivedType(3, typeof(B<C>))]
    public class A<T>

**Comment by inethui** [comment]
Thanks for the suggestion. Does Aqla support all .NET framework collection types?

**Comment by AqlaSolutions** [comment]
It supports those which implement `IList<T>` or `IDictionary<K,V>`

**Comment by inethui** [comment]
Thanks. This is really helpful.
