### ISSUE TITLE
Is nuget package 2.0.1 the latest version?

### ISSUE THREAD

**Issue by inethui** [AqlaSolutions/AqlaSerializer#34]
We get the nuget package 2.0.1, but it doesn't seem to have the latest enhancements. For example, it doesn't support IReadOnlyDictionary. Can you please put the latest version in nuget?

**Comment by AqlaSolutions** [comment]
2.0.1.1032 is the latest version and it should have all these enhancements.

**Comment by AqlaSolutions** [comment]
It seems that some specific platforms used wrong binaries. I listed the 2.0.1.1033 version which should fix this issue.
