### ISSUE TITLE
Invalid serialization operation with wire-type None

### ISSUE THREAD

**Issue by inethui** [AqlaSolutions/AqlaSerializer#35]
The following test throws AqlaSerializer.ProtoException : AqlaSerializer.ProtoException : Invalid serialization operation with wire-type None, waiting for wire type of field number 2, position 5

Any idea why? Thanks

```
        [Fact]
        public void TestNamedTuples()
        {
            (int Number1, int? Number2) obj = (1, null);

            var clone = Serializer.DeepClone(obj);

            Assert.Equal(clone.Number1, obj.Number1);
            Assert.Equal(clone.Number2, obj.Number2);
        }
```

**Comment by inethui** [comment]
If I change the test to the followings, I get another error from the DeepClone method: System.InvalidProgramException : Common Language Runtime detected an invalid program.
```
        [Fact]
        public void TestNamedTuples()
        {
            (int Number1, int? Number2) obj = (1, 2);

            var clone = Serializer.DeepClone(obj);

            Assert.Equal(clone.Number1, obj.Number1);
            Assert.Equal(clone.Number2, obj.Number2);
        }
```

**Comment by inethui** [comment]
BTW, the above code works for Protobuf-net.

**Comment by AqlaSolutions** [comment]
Probably value tuples are not supported yet. It's the next thing to fix.

**Comment by AqlaSolutions** [comment]
This is fixed in develop branch, please check.

**Comment by inethui** [comment]
I've verified that this issue is fixed in develop branch.
