### ISSUE TITLE
RuntimeTypeModel.Default.CompileInPlace is too slow

### ISSUE THREAD

**Issue by inethui** [AqlaSolutions/AqlaSerializer#38]
We have more than 5800 classes which are registered with "RuntimeTypeModel.Default". However if I run CompileInPlace against the model, it takes more than 3 minutes. Is there a way to speed this up?

**Comment by AqlaSolutions** [comment]
No, but you can run `Model.Compile("assembly.dll")` once as a part of your publish process instead of using `CompileInPlace` each time. Though, in this case serializers can't access private members of your classes.

**Comment by AqlaSolutions** [comment]
And for debugging experience you can run without serializers compilation at all to have faster startup times (`AutoCompile = false`) though serialization itself will be slow.

**Comment by inethui** [comment]
We have to access the private fields of classes. How does Aqla access private fields? Is it through generated IL code or use reflection APIs?

**Comment by AqlaSolutions** [comment]
1. Reflection if `AutoCompile = false`
2. In-memory IL if  `CompleInPlace()` is called
3. Can't access from disk dll assembly if `Compile` is called

**Comment by inethui** [comment]
This is very helpful, thank you.
