### ISSUE TITLE
Progress Callback

### ISSUE THREAD

**Issue by ab-tools** [AqlaSolutions/AqlaSerializer#4]
As it's not totally related and more like a question, I thought I better open another issue here for that.

With the bigger database I have - even with the older, faster version - it takes about 30 sec. to serialize. That's not a problem to let the user wait for, but it would be great to be able to show some sort of progress to the user.

Is there any chance that AqlaSerializer could send a callback with some progress update like 1,000 of 10,000 objects done or similar?

Although I'm afraid that it won't be easily possible due to the stream serialization structure of protobuf, but I thought I just ask anyway - maybe you have an idea about it. :-)

**Comment by AqlaSolutions** [comment]
Progress is something that requires `current` and `total` numbers. Unfortunately even AqlaSerializer itself doesn't know preliminary how many objects or bytes will be in `total`. If you expect some size of data you may use your wrapper around stream to track when its length is being changed.

**Comment by ab-tools** [comment]
Yes, thought that already, but just wanted to ask. ;-)

Thanks anyway!
