### ISSUE TITLE
"Unable to determine member" when running obfuscated code

### ISSUE THREAD

**Issue by inethui** [AqlaSolutions/AqlaSerializer#47]
We got the error "Unable to determine member" when running the obfuscated code with Aqla. After some investigation we found the cause:
Obfuscation could assign the same name for a field and method. This is legal in IL, but not allowed in C#. When we register a field with Aqla by calling "metaType.AddField(Index, fieldName)", Aqla internally calls the following code:
```
private ValueMember AddField(int fieldNumber, string memberName, Type itemType, Type defaultType, object defaultValue)
{
    if (Type.IsArray) throw new InvalidOperationException("Can't add fields to array type");
    MemberInfo mi = null;
    MemberInfo[] members = Type.GetMember(memberName, Helpers.IsEnum(Type) ? BindingFlags.Static | BindingFlags.Public : BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
    if (members != null && members.Length == 1) mi = members[0];
    if (mi == null) throw new ArgumentException("Unable to determine member: " + memberName, nameof(memberName));
```
If a method and a field have the same member name (which is in our case),  "Type.GetMember" will return more than 1 results. This results in "mi == null" and thus the exception "Unable to determine member".
Can Aqla be enhanced to handle this case?

**Comment by AqlaSolutions** [comment]
This was fixed by https://github.com/AqlaSolutions/AqlaSerializer/pull/49 (in develop branch now)
