### ISSUE TITLE
Is there a way to re-compile the runtime type model as a dll?

### ISSUE THREAD

**Issue by inethui** [AqlaSolutions/AqlaSerializer#56]
Our model is very large, it contains more than 10000 classes. Compiling it explicitly takes about 7-8 minutes, compiling it on-demand takes about 30 - 40 seconds. Both are not acceptable to our application. Is there a way to re-compile it into dll at build time, so the runtime overhead can be eliminated?

**Comment by AqlaSolutions** [comment]
Yes, use the `RuntimeTypeModel.Compile` overload that accepts output dll name. Though, it will not allow you to serialize private members. You can integrate it into your pipeline as a post-build step.

**Comment by inethui** [comment]
Thank you! I'll try that.
